package com.company.bot.enums;

public enum UserQuestionnaireStatus {
        DEFAULT ,NAME, SURNAME, BIRTH_DATE, GENDER, PHONE, WEIGHT, HEIGHT,REGION,
    BLOOD_PRESSURE, HEART_BEAT, DIABETES, TEMPERATURE,
    COMPLAINTS_INFO_WRITE, COMPLAINTS_STARTED_TIME,
    DRUGS_LIST, CIGARETTE, DISEASES_LIST, INSPECTION_PAPERS
}