package com.company.enums;

public enum UserQuestionnaireStatus {
    NAME, SURNAME, BIRTH_DATE, GENDER, PHONE, WEIGHT, HEIGHT,DEFAULT, BLOOD_PRESSURE, HEART_BEAT, DIABETES, TEMPRATURE, COMPLAINTS_INFO_WRITE,COMPLAINTS_STARTED_TIME,
    DRUGS_LIST, CIGARETTE, DISEASES_LIST, INSPECTION_PAPERS
}